// Package hints provides the DNSKEY and NS/A/AAAA records for the root DNS zone
package hints

// generated by hints/generate/generate_hints.go at 2016-09-10 22:56:05.620997281 -0700 PDT
// DO NOT EDIT BY HAND

import (
	"net"

	"github.com/miekg/dns"
)

// RootKeys contains the DNSKEY records for the root zone
var RootKeys = []dns.RR{

	&dns.DNSKEY{
		Hdr: dns.RR_Header{
			Name:   ".",
			Rrtype: 48,
			Class:  1,
			Ttl:    172800,
		},
		Flags:     257,
		Protocol:  3,
		Algorithm: 8,
		PublicKey: "AwEAAagAIKlVZrpC6Ia7gEzahOR+9W29euxhJhVVLOyQbSEW0O8gcCjFFVQUTf6v58fLjwBd0YI0EzrAcQqBGCzh/RStIoO8g0NfnfL2MTJRkxoXbfDaUeVPQuYEhg37NZWAJQ9VnMVDxP/VHL496M/QZxkjf5/Efucp2gaDX6RS6CXpoY68LsvPVjR0ZSwzz1apAzvN9dlzEheX7ICJBBtuA6G3LQpzW5hOA2hzCTMjJPJ8LbqF6dsV6DoBQzgul0sGIcGOYl7OyQdXfZ57relSQageu+ipAdTTJ25AsRTAoub8ONGcLmqrAmRLKBP1dfwhYB4N7knNnulqQxA+Uk1ihz0=",
	},

	&dns.DNSKEY{
		Hdr: dns.RR_Header{
			Name:   ".",
			Rrtype: 48,
			Class:  1,
			Ttl:    172800,
		},
		Flags:     256,
		Protocol:  3,
		Algorithm: 8,
		PublicKey: "AwEAAcCsATzyk1Hj1xabagAGWi9sZSbB+igdzDM8CMZ5fPcOb314yP9/lmvidoBuApPlMVwlz0lXaj6gzyjoOKBveoDD0VyHTqjCDg9UrcDoClNZciR2sHZoaMZp2yVNFyaC+7MkA8lsrCShieYPEowSjQdkvY5ONlEib/ATXdmAhfgB",
	},
}

// RootNameservers contains the NS and A/AAAA records for the root zone nameservers
var RootNameservers = []dns.RR{

	&dns.NS{
		Hdr: dns.RR_Header{
			Name:   ".",
			Rrtype: 2,
			Class:  1,
			Ttl:    3600000,
		},

		Ns: "A.ROOT-SERVERS.NET.",
	},

	&dns.A{
		Hdr: dns.RR_Header{
			Name:   "A.ROOT-SERVERS.NET.",
			Rrtype: 1,
			Class:  1,
			Ttl:    3600000,
		},

		A: net.IP{198, 41, 0, 4},
	},

	&dns.AAAA{
		Hdr: dns.RR_Header{
			Name:   "A.ROOT-SERVERS.NET.",
			Rrtype: 28,
			Class:  1,
			Ttl:    3600000,
		},

		AAAA: net.IP{32, 1, 5, 3, 186, 62, 0, 0, 0, 0, 0, 0, 0, 2, 0, 48},
	},

	&dns.NS{
		Hdr: dns.RR_Header{
			Name:   ".",
			Rrtype: 2,
			Class:  1,
			Ttl:    3600000,
		},

		Ns: "B.ROOT-SERVERS.NET.",
	},

	&dns.A{
		Hdr: dns.RR_Header{
			Name:   "B.ROOT-SERVERS.NET.",
			Rrtype: 1,
			Class:  1,
			Ttl:    3600000,
		},

		A: net.IP{192, 228, 79, 201},
	},

	&dns.AAAA{
		Hdr: dns.RR_Header{
			Name:   "B.ROOT-SERVERS.NET.",
			Rrtype: 28,
			Class:  1,
			Ttl:    3600000,
		},

		AAAA: net.IP{32, 1, 5, 0, 0, 132, 0, 0, 0, 0, 0, 0, 0, 0, 0, 11},
	},

	&dns.NS{
		Hdr: dns.RR_Header{
			Name:   ".",
			Rrtype: 2,
			Class:  1,
			Ttl:    3600000,
		},

		Ns: "C.ROOT-SERVERS.NET.",
	},

	&dns.A{
		Hdr: dns.RR_Header{
			Name:   "C.ROOT-SERVERS.NET.",
			Rrtype: 1,
			Class:  1,
			Ttl:    3600000,
		},

		A: net.IP{192, 33, 4, 12},
	},

	&dns.AAAA{
		Hdr: dns.RR_Header{
			Name:   "C.ROOT-SERVERS.NET.",
			Rrtype: 28,
			Class:  1,
			Ttl:    3600000,
		},

		AAAA: net.IP{32, 1, 5, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 12},
	},

	&dns.NS{
		Hdr: dns.RR_Header{
			Name:   ".",
			Rrtype: 2,
			Class:  1,
			Ttl:    3600000,
		},

		Ns: "D.ROOT-SERVERS.NET.",
	},

	&dns.A{
		Hdr: dns.RR_Header{
			Name:   "D.ROOT-SERVERS.NET.",
			Rrtype: 1,
			Class:  1,
			Ttl:    3600000,
		},

		A: net.IP{199, 7, 91, 13},
	},

	&dns.AAAA{
		Hdr: dns.RR_Header{
			Name:   "D.ROOT-SERVERS.NET.",
			Rrtype: 28,
			Class:  1,
			Ttl:    3600000,
		},

		AAAA: net.IP{32, 1, 5, 0, 0, 45, 0, 0, 0, 0, 0, 0, 0, 0, 0, 13},
	},

	&dns.NS{
		Hdr: dns.RR_Header{
			Name:   ".",
			Rrtype: 2,
			Class:  1,
			Ttl:    3600000,
		},

		Ns: "E.ROOT-SERVERS.NET.",
	},

	&dns.A{
		Hdr: dns.RR_Header{
			Name:   "E.ROOT-SERVERS.NET.",
			Rrtype: 1,
			Class:  1,
			Ttl:    3600000,
		},

		A: net.IP{192, 203, 230, 10},
	},

	&dns.AAAA{
		Hdr: dns.RR_Header{
			Name:   "E.ROOT-SERVERS.NET.",
			Rrtype: 28,
			Class:  1,
			Ttl:    3600000,
		},

		AAAA: net.IP{32, 1, 5, 0, 0, 168, 0, 0, 0, 0, 0, 0, 0, 0, 0, 14},
	},

	&dns.NS{
		Hdr: dns.RR_Header{
			Name:   ".",
			Rrtype: 2,
			Class:  1,
			Ttl:    3600000,
		},

		Ns: "F.ROOT-SERVERS.NET.",
	},

	&dns.A{
		Hdr: dns.RR_Header{
			Name:   "F.ROOT-SERVERS.NET.",
			Rrtype: 1,
			Class:  1,
			Ttl:    3600000,
		},

		A: net.IP{192, 5, 5, 241},
	},

	&dns.AAAA{
		Hdr: dns.RR_Header{
			Name:   "F.ROOT-SERVERS.NET.",
			Rrtype: 28,
			Class:  1,
			Ttl:    3600000,
		},

		AAAA: net.IP{32, 1, 5, 0, 0, 47, 0, 0, 0, 0, 0, 0, 0, 0, 0, 15},
	},

	&dns.NS{
		Hdr: dns.RR_Header{
			Name:   ".",
			Rrtype: 2,
			Class:  1,
			Ttl:    3600000,
		},

		Ns: "G.ROOT-SERVERS.NET.",
	},

	&dns.A{
		Hdr: dns.RR_Header{
			Name:   "G.ROOT-SERVERS.NET.",
			Rrtype: 1,
			Class:  1,
			Ttl:    3600000,
		},

		A: net.IP{192, 112, 36, 4},
	},

	&dns.NS{
		Hdr: dns.RR_Header{
			Name:   ".",
			Rrtype: 2,
			Class:  1,
			Ttl:    3600000,
		},

		Ns: "H.ROOT-SERVERS.NET.",
	},

	&dns.A{
		Hdr: dns.RR_Header{
			Name:   "H.ROOT-SERVERS.NET.",
			Rrtype: 1,
			Class:  1,
			Ttl:    3600000,
		},

		A: net.IP{198, 97, 190, 53},
	},

	&dns.AAAA{
		Hdr: dns.RR_Header{
			Name:   "H.ROOT-SERVERS.NET.",
			Rrtype: 28,
			Class:  1,
			Ttl:    3600000,
		},

		AAAA: net.IP{32, 1, 5, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 83},
	},

	&dns.NS{
		Hdr: dns.RR_Header{
			Name:   ".",
			Rrtype: 2,
			Class:  1,
			Ttl:    3600000,
		},

		Ns: "I.ROOT-SERVERS.NET.",
	},

	&dns.A{
		Hdr: dns.RR_Header{
			Name:   "I.ROOT-SERVERS.NET.",
			Rrtype: 1,
			Class:  1,
			Ttl:    3600000,
		},

		A: net.IP{192, 36, 148, 17},
	},

	&dns.AAAA{
		Hdr: dns.RR_Header{
			Name:   "I.ROOT-SERVERS.NET.",
			Rrtype: 28,
			Class:  1,
			Ttl:    3600000,
		},

		AAAA: net.IP{32, 1, 7, 254, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 83},
	},

	&dns.NS{
		Hdr: dns.RR_Header{
			Name:   ".",
			Rrtype: 2,
			Class:  1,
			Ttl:    3600000,
		},

		Ns: "J.ROOT-SERVERS.NET.",
	},

	&dns.A{
		Hdr: dns.RR_Header{
			Name:   "J.ROOT-SERVERS.NET.",
			Rrtype: 1,
			Class:  1,
			Ttl:    3600000,
		},

		A: net.IP{192, 58, 128, 30},
	},

	&dns.AAAA{
		Hdr: dns.RR_Header{
			Name:   "J.ROOT-SERVERS.NET.",
			Rrtype: 28,
			Class:  1,
			Ttl:    3600000,
		},

		AAAA: net.IP{32, 1, 5, 3, 12, 39, 0, 0, 0, 0, 0, 0, 0, 2, 0, 48},
	},

	&dns.NS{
		Hdr: dns.RR_Header{
			Name:   ".",
			Rrtype: 2,
			Class:  1,
			Ttl:    3600000,
		},

		Ns: "K.ROOT-SERVERS.NET.",
	},

	&dns.A{
		Hdr: dns.RR_Header{
			Name:   "K.ROOT-SERVERS.NET.",
			Rrtype: 1,
			Class:  1,
			Ttl:    3600000,
		},

		A: net.IP{193, 0, 14, 129},
	},

	&dns.AAAA{
		Hdr: dns.RR_Header{
			Name:   "K.ROOT-SERVERS.NET.",
			Rrtype: 28,
			Class:  1,
			Ttl:    3600000,
		},

		AAAA: net.IP{32, 1, 7, 253, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1},
	},

	&dns.NS{
		Hdr: dns.RR_Header{
			Name:   ".",
			Rrtype: 2,
			Class:  1,
			Ttl:    3600000,
		},

		Ns: "L.ROOT-SERVERS.NET.",
	},

	&dns.A{
		Hdr: dns.RR_Header{
			Name:   "L.ROOT-SERVERS.NET.",
			Rrtype: 1,
			Class:  1,
			Ttl:    3600000,
		},

		A: net.IP{199, 7, 83, 42},
	},

	&dns.AAAA{
		Hdr: dns.RR_Header{
			Name:   "L.ROOT-SERVERS.NET.",
			Rrtype: 28,
			Class:  1,
			Ttl:    3600000,
		},

		AAAA: net.IP{32, 1, 5, 0, 0, 159, 0, 0, 0, 0, 0, 0, 0, 0, 0, 66},
	},

	&dns.NS{
		Hdr: dns.RR_Header{
			Name:   ".",
			Rrtype: 2,
			Class:  1,
			Ttl:    3600000,
		},

		Ns: "M.ROOT-SERVERS.NET.",
	},

	&dns.A{
		Hdr: dns.RR_Header{
			Name:   "M.ROOT-SERVERS.NET.",
			Rrtype: 1,
			Class:  1,
			Ttl:    3600000,
		},

		A: net.IP{202, 12, 27, 33},
	},

	&dns.AAAA{
		Hdr: dns.RR_Header{
			Name:   "M.ROOT-SERVERS.NET.",
			Rrtype: 28,
			Class:  1,
			Ttl:    3600000,
		},

		AAAA: net.IP{32, 1, 13, 195, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 53},
	},
}
